#!/bin/bash


#function to take an error message and output it to stderr
function error()
{
echo "Error - $1" >>/dev/stderr
}

#method to load matrix from a file or from stdin courtesy of the hints part of the assignment page

datafilepath="datafile$$"
if [ "$#" = "0" ]
then
	error "busted, you didn't supply any arguments"
	exit 1
elif [ "$#" = "1" ]
then
	cat > "$datafilepath"
elif [ "$#" = "2" ]
then
	datafilepath=$2
	if [ ! -f "$datafilepath" ]
	then
		error "busted, that file does not exist"
		exit 1
	fi
elif [ "$#" = "3" ]
then
	datafilepath=$2
	data2filepath=$3

	if [ ! -f "$datafilepath" ] || [ ! -f "$data2filepath" ]
	then
		error "busted, a file does not exist"
		exit 1
	fi
else
	error "too many arguments"
	exit 1
fi

#checking if the dang ol files exist


function dims()
{

if [ ! "$#" = "1" ]
then
	error "busted, wrong numner of arguments"
	exit 1
fi

width="1"
height="0"
while IFS= read line 
do
	((height++))
done < "$datafilepath"
read -r line < "$datafilepath"
for (( i=0; i<${#line}; i++  ))
do
	
	if [ "${line:$i:1}" = "	" ]
	then
		((width++))
	fi
done

echo "$height $width"
return 0
}

function transpose()
{
echo 'running transpose'
}

function mean()
{
echo 'running mean'
}

function add()
{
echo 'running add'
}

function multiply()
{
echo 'running multiply'
}

$1 "${@:2}"
