#!/bin/bash


#function to take an error message and output it to stderr
function error()
{
echo "Error - $1" >>/dev/stderr
}

#method to load matrix from a file or from stdin courtesy of the hints part of the assignment page

datafilepath="datafile$$"
if [ "$#" = "0" ]
then
	error "busted, you didn't supply any arguments"
	exit 1
elif [ "$#" = "1" ]
then
	cat > "$datafilepath"
elif [ "$#" = "2" ]
then
	datafilepath=$2
fi

#checking if the dang ol files exist


function dims()
{
echo 'running dims'

return 0
}

function transpose()
{
echo 'running transpose'
}

function mean()
{
echo 'running mean'
}

function add()
{
echo 'running add'
}

function multiply()
{
echo 'running multiply'
}

$1 "${@:2}"
